### ISSUE TITLE
User Story: Lorry Arrival and Ticket Processing

### ISSUE THREAD

**Issue by tbm-2303** [tbm-2303/CDMS#1]
As a warehouse staff member, I want to process the ticket presented by the driver so that the shipment can be accepted if the depot has capacity. A job should be raised detailing where the chemicals should be stored.

### Tasks
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13

**Comment by tbm-2303** [comment]
### Tasks
- [ ] Design the data model for tickets and jobs
- [ ] Implement the ticket processing logic
- [ ] Create a user interface for ticket input
- [ ] Write unit tests for ticket processing
- [ ] Document the ticket processing flow

**Comment by tbm-2303** [comment]
### Tasks
- [ ] Design the data model for tickets and jobs
- [ ] Implement the ticket processing logic
- [ ] Create a user interface for ticket input
- [ ] Write unit tests for ticket processing
- [ ] Document the ticket processing flow
