### ISSUE TITLE
User Story: Auditing Information

### ISSUE THREAD

**Issue by tbm-2303** [tbm-2303/CDMS#2]
As a compliance officer, I want the system to provide auditing information showing the storage and movement of chemicals so that we can ensure compliance with regulations.

**Comment by tbm-2303** [comment]
### Tasks
- [ ] Define the data model for auditing information
- [ ] Implement the auditing functionality
- [ ] Create reports for storage and movement of chemicals
- [ ] Write unit tests for auditing functionality
- [ ] Document the auditing process
