### ISSUE TITLE
tilføj ønsker 

### ISSUE THREAD

**Issue by tbm-2303** [tbm-2303/CDMS#4]
### Tasks
- [ ] Define the data model for auditing information
- [ ] Implement the auditing functionality
- [ ] Create reports for storage and movement of chemicals
